// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hackaton.Infrastructure.Persistence;

#nullable disable

namespace hackaton.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("hackaton.Infrastructure.Persistence.Entities.ArchivoProcesado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaProceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Procesados")
                        .HasColumnType("int");

                    b.Property<int>("Rechazados")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NombreArchivo")
                        .IsUnique();

                    b.ToTable("ArchivoControl", (string)null);
                });

            modelBuilder.Entity("hackaton.Infrastructure.Persistence.Entities.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArchivoProcesadoId")
                        .HasColumnType("int");

                    b.Property<string>("Cuenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoProcesadoId");

                    b.ToTable("Transaccion", (string)null);
                });

            modelBuilder.Entity("hackaton.Infrastructure.Persistence.Entities.Transaccion", b =>
                {
                    b.HasOne("hackaton.Infrastructure.Persistence.Entities.ArchivoProcesado", "ArchivoProcesado")
                        .WithMany("Transacciones")
                        .HasForeignKey("ArchivoProcesadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivoProcesado");
                });

            modelBuilder.Entity("hackaton.Infrastructure.Persistence.Entities.ArchivoProcesado", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
